name: DHIS2 Docker 

on:
  push:
    branches:
      - master

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build238:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dhis2/dhis2app/Dockerfile
          push: true
          no-cache: true
          build-args: |
            version="2.38/dhis2-stable-2.38.3.1"
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dhis2:2.38.3.1-jdk11-t9
  build239:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dhis2/dhis2app/Dockerfile
          push: true
          no-cache: true
          build-args: |
            version="2.39/dhis2-stable-2.39.1.2"
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dhis2:2.39.1.2-jdk11-t9
  build240:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dhis2/dhis2app/Dockerfile
          push: true
          no-cache: true
          build-args: |
            version="40/dhis2-stable-40.0.0"
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dhis2:2.40.0.0-jdk11-t9