name: Apache Superset Docker 

on:
  push:
    branches:
      - master

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  buildSupersetVersions:
    strategy:
      matrix: 
        major_version: ['4.0.2','4.0.2-websocket','4.0.2-dockerize'] 
    name: Build Apache Superset version

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./superset/Dockerfile
          push: true
          no-cache: true
          build-args: |
            superset_version=${{ matrix.major_version }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/superset:${{ matrix.major_version}}